# Generated by Django 6.0.5 on 2026-05-06 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revendedores', '0001_initial'),
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='codigo_pedido',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('boleto_1x', 'Boleto 1x'), ('boleto_2x', 'Boleto 2x'), ('boleto_3x', 'Boleto 3x'), ('cartao_credito', 'Cartão de Crédito'), ('pix', 'Pix'), ('dinheiro', 'Dinheiro')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='revendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='revendedores.revendedor'),
        ),
    ]
