# Generated by Django 6.0.5 on 2026-05-07 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franquias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='franquia',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='franquia',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
