# Generated by Django 6.0.5 on 2026-05-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('operador', 'Operador'), ('colaborador', 'Colaborador')], default='colaborador', max_length=20),
        ),
    ]
