# Generated by Django 6.0.5 on 2026-05-06 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('franquias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('franquia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revendedores', to='franquias.franquia')),
            ],
        ),
    ]
