# Generated by Django 6.0.5 on 2026-05-06 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franquias', '0001_initial'),
        ('revendedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revendedor',
            name='franquia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revendedores', to='franquias.franquia'),
        ),
    ]
