# Generated by Django 6.0.5 on 2026-05-06 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revendedores', '0002_alter_revendedor_franquia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revendedor',
            name='codigo',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
